In [1]:
import numpy as np
import pandas as pd
import matplotlib

In [ ]:
a=[1,2,3,4,5]
data=np.array(a)
print(a, type(a))
print(data, type(data))
print(sum(a))
print(sum(data))

In [ ]:
data=np.random.rand(50)
print(data)

In [ ]:
seri=pd.Series([10,20,30,40])
print(seri)
seri.index=['가','나','다','라']
print(seri)
print(seri[['가','다']])

In [ ]:
data_set=np.random.rand(10,3)
print(data_set)

In [ ]:
df=pd.DataFrame(data_set,columns=['A','B','C'])
df

In [ ]:
name=['홍길동','이순신','장영실','최무선','임꺽정']
kor=[50,70,80,75,60]
math=[70,85,80,95,90]
data={'name':name, 'kor':kor, 'math':math}
df=pd.DataFrame(data)
df


In [ ]:
a=[10,20,30]
np_arr=np.array(a)
print(a,type(a))
print(np_arr,type(np_arr))

In [ ]:
data1=np.random.rand(10)
data2=np.random.rand(10,3)
print(data1)
print(data2)

In [ ]:
seri1=pd.Series(a)
print(seri1)

In [ ]:
df1=pd.DataFrame(data2,columns=['a','b','c'])
df1

In [ ]:
name=['홍길동','홍길수','홍길숙']
age=[20,25,30]
gender=['남','남','여']
data={'name':name,'age':age,'gender':gender}

df=pd.DataFrame(data)
print(df)
df

In [ ]:
seri=pd.Series(np.random.rand(10))
seri

In [ ]:
seri.plot()

In [ ]:
matplotlib.style.use("ggplot")
seri.plot(kind="pie")

In [ ]:
df1.plot(kind="area", stacked=False) #kind:bar, barh, area, pie

In [ ]:
seri=pd.Series(np.random.rand(5),index=['A','B','C','D','E'], name="Seri1")
seri.plot(kind='pie', autopct='%.2f',fontsize=20, figsize=(8,6))

In [ ]:
a=[1,3,5]
x=np.array(a)
print(np.mean(a),x.mean(),np.mean(x))

In [ ]:
data=[1,2,3,4]
x=np.array(data)
#data.mean()
x.mean()

In [ ]:
data=[[1,2,3],[3,4,5]]
arr2=np.array(data)
arr2

In [ ]:
data2=[1,2,3,4,5,6]
arr2=np.array(data2).reshape(2,3)
print(arr2)
print(type(arr2))
print(arr2.shape)

In [ ]:
list1=[[1,11,101],[2,12,102],[3,13,103]]
print(list1[:][1])
#print(list1[1,1])
#print(list1[:,1])

In [ ]:
np_arr=np.array(list1)
print(np_arr[::2,1])
print(np_arr[:,::2])

In [ ]:
x=np.random.rand(5)
y=np.random.rand(5)
print(x)
print(y)

In [ ]:
print(np.minimum(x,y))
print(np.maximum(x,y))

In [ ]:
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x//y)
print(x**y)
print(x+6)
print(x*2)

In [ ]:
list1=[1,2,3,4,5]
list2=[10,20,30,40,50]
print(list1+list2)

In [ ]:
a=np.arange(1,101).reshape(10,10)
print(a)

In [ ]:
print(np.sqrt(a))
print(np.mean(a))
print(np.sum(a))
print(np.sum(a,axis=0)) #axis 0, 열방향
print(np.sum(a,axis=1)) #axis 1, 행방향
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

In [ ]:
b=[[5,3,4],[3,5,1],[7,6,9]]
arr_b=np.array(b)
print(arr_b)

In [ ]:
print(np.sort(b))
print(np.sort(b,axis=0)) #열
print(np.sort(b,axis=1)) #행
print(np.sort(b,axis=0)[::-1])
print(np.sort(b,axis=1)[::-1]) #안됨
print(arr_b.transpose())

In [ ]:
a1=np.arange(1,13).reshape(3,4)
print(a1)
print(a1.transpose())

In [ ]:
a=np.array([1,1,3,3,4,5])
print(np.unique(a))

In [ ]:
a2=np.arange(1,13).reshape(3,4)
print(a2)

In [ ]:
a3=np.arange(12).reshape(3,4)
print(a3)

In [ ]:
print(a2>5)
print(np.all(a2>5))
print(np.any(a2>5))
print(a2>a3)

In [ ]:
a=np.linspace(0,12,4,retstep=True,endpoint=False)
print(a)
b=np.logspace(1,2,10, endpoint=False) #log10100
print(b)

In [2]:
data=np.loadtxt('data/ml-1m/ratings.dat',delimiter='::',dtype=np.int64)

In [3]:
print(data[:5,:])
print(data.shape)

[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]]
(1000209, 4)


In [4]:
#전체 평균
mean_rating_total=data[:,2].mean() #np.mean(data[:,2])
mean_rating_total

3.581564453029317

In [5]:
#사용자 Id 추출
user_ids=np.unique(data[:,0])
print(user_ids[:10])
print(user_ids.shape)

[ 1  2  3  4  5  6  7  8  9 10]
(6040,)


In [9]:
#사용자별 평균 평점
mean_values=[]
#data_for_user=data[data[:,0]==1]
#print(data_for_user)
for user_id in user_ids:
    data_for_user=data[data[:,0]==user_id]
    #print(data_for_user)
    value=data_for_user[:,2].mean()
    mean_values.append([user_id,value])

mean_values[:5]

[[1, 4.188679245283019],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.190476190476191],
 [5, 3.1464646464646466]]

In [11]:
mean_array=np.array(mean_values,dtype=np.float32)
print(mean_array[:10])
print(mean_array.shape)

[[ 1.         4.188679 ]
 [ 2.         3.7131784]
 [ 3.         3.9019608]
 [ 4.         4.1904764]
 [ 5.         3.1464646]
 [ 6.         3.9014084]
 [ 7.         4.322581 ]
 [ 8.         3.884892 ]
 [ 9.         3.7358491]
 [10.         4.114713 ]]
(6040, 2)


In [12]:
np.savetxt("data/ml-1m/result1.csv",mean_array,fmt='%.2f',delimiter=',')

In [14]:
#영화 Id 추출
movie_ids=np.unique(data[:,1])
print(movie_ids[:10])
print(movie_ids.shape)

[ 1  2  3  4  5  6  7  8  9 10]
(3706,)


In [16]:
#영화별 평균 평점
mean_values2=[]
#data_for_movie=data[data[:,1]==1]
#print(data_for_movie)
for movie_id in movie_ids:
    data_for_movie=data[data[:,1]==movie_id]
    #print(data_for_user)
    value=data_for_movie[:,2].mean()
    mean_values2.append([movie_id,value])

mean_values2[:5]

[[1, 4.146846413095811],
 [2, 3.20114122681883],
 [3, 3.01673640167364],
 [4, 2.7294117647058824],
 [5, 3.0067567567567566]]

In [17]:
mean_array2=np.array(mean_values2,dtype=np.float32)
print(mean_array2[:10])
print(mean_array2.shape)

[[ 1.         4.1468463]
 [ 2.         3.201141 ]
 [ 3.         3.0167365]
 [ 4.         2.7294118]
 [ 5.         3.0067568]
 [ 6.         3.8787234]
 [ 7.         3.4104803]
 [ 8.         3.014706 ]
 [ 9.         2.6568627]
 [10.         3.5405405]]
(3706, 2)


In [18]:
np.savetxt("data/ml-1m/result2.csv",mean_array2,fmt='%.2f',delimiter=',')