In [12]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense

In [10]:
#x_data=np.array([2,4,6,8,10,12,14,16,18,20]).astype('float32')
x_data=np.array([[2,4],[4,11],[6,6],[8,5],[10,7],[12,16],[14,8],[16,3],[18,7]]).astype('float32')
#t_data=np.array([0,0,0,0,0,0,1,1,1,1]).astype('float32')
t_data=np.array([0,0,0,0,1,1,1,1,1]).astype('float32')

In [18]:
model=tf.keras.models.Sequential()
model.add(Flatten(input_shape=(2,)))
#model.add(tf.keras.layers.Dense(10,input_shape=(1,),activation='sigmoid'))
model.add(tf.keras.layers.Dense(8,activation='sigmoid'))
model.add(tf.keras.layers.Dense(1,activation='sigmoid'))

In [19]:
model.compile(tf.keras.optimizers.SGD(learning_rate=0.1),
             loss='binary_crossentropy',metrics=['accuracy'])

model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_1 (Flatten)         (None, 2)                 0         
                                                                 
 dense_4 (Dense)             (None, 8)                 24        
                                                                 
 dense_5 (Dense)             (None, 1)                 9         
                                                                 
Total params: 33
Trainable params: 33
Non-trainable params: 0
_________________________________________________________________


In [20]:
hist=model.fit(x_data,t_data,epochs=500)

Epoch 1/500
1/1 [==============================] - 0s 266ms/step - loss: 0.7037 - accuracy: 0.5556
Epoch 2/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6999 - accuracy: 0.5556
Epoch 3/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6966 - accuracy: 0.5556
Epoch 4/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6938 - accuracy: 0.5556
Epoch 5/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6914 - accuracy: 0.5556
Epoch 6/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6894 - accuracy: 0.5556
Epoch 7/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6876 - accuracy: 0.5556
Epoch 8/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6861 - accuracy: 0.5556
Epoch 9/500
1/1 [==============================] - 0s 5ms/step - loss: 0.6848 - accuracy: 0.5556
Epoch 10/500
1/1 [==============================] - 0s 6ms/step - loss: 0.6836 - accuracy: 0.5556
Epoch 11/500
1/1 [=========

In [21]:
#test_data=np.array([0.5,3.0,3.5,11.0,13.0,31.0])
test_data=np.array([[0.5,0.4],[3.0,2.0],[3.5,0.4],[11.0,2.1],[13.0,0.0],[31.0,1.0]])
sigmoid_value=model.predict(test_data)

logical_value=tf.cast(sigmoid_value>0.5,
                     dtype=tf.float32)

for i in range(len(test_data)):
    print(test_data[i],
         sigmoid_value[i],
         logical_value.numpy()[i])

[0.5 0.4] [0.08938298] [0.]
[3. 2.] [0.2185973] [0.]
[3.5 0.4] [0.3821738] [0.]
[11.   2.1] [0.8605155] [1.]
[13.  0.] [0.89205813] [1.]
[31.  1.] [0.9211389] [1.]


In [22]:
model.weights

[<tf.Variable 'dense_4/kernel:0' shape=(2, 8) dtype=float32, numpy=
 array([[-0.6578362 , -0.3317128 ,  0.43057212, -0.27228278,  0.2756627 ,
         -0.2832964 , -0.6227237 , -0.7023247 ],
        [-0.39559752, -0.68401444,  0.61111474,  0.08935273, -0.03698606,
          0.0498968 ,  0.98159504, -0.22469445]], dtype=float32)>,
 <tf.Variable 'dense_4/bias:0' shape=(8,) dtype=float32, numpy=
 array([ 0.04240362,  0.00682897,  0.01245051,  0.08449423, -1.1016408 ,
         1.0005987 ,  0.3343638 , -0.00533631], dtype=float32)>,
 <tf.Variable 'dense_5/kernel:0' shape=(8, 1) dtype=float32, numpy=
 array([[-0.8254261 ],
        [-0.15158035],
        [-0.04801879],
        [-0.55736655],
        [ 2.4197824 ],
        [-2.222301  ],
        [-1.3188391 ],
        [-0.04625843]], dtype=float32)>,
 <tf.Variable 'dense_5/bias:0' shape=(1,) dtype=float32, numpy=array([0.0887467], dtype=float32)>]