In [1]:
def numerical_derivative(f,x):
    delta_x = 1e-4
    return (f(x+delta_x)-f(x-delta_x))/(2*delta_x)

In [2]:
def my_func1(x):
    return x**2

In [4]:
result=numerical_derivative(my_func1,3)
print("result ==",result)

result == 6.000000000012662


In [5]:
import numpy as np

def my_func2(x):
    return 3*x*(np.exp(x))

In [6]:
result=numerical_derivative(my_func2,2)
print("result ==",result)

result == 66.50150507518049


In [7]:
print("3*exp(2)+3*2*exp(2)==",end='')
print(3*np.exp(2)+3*2*np.exp(2))

3*exp(2)+3*2*exp(2)==66.50150489037586


In [11]:
def my_func3(x):
    return 3*x**2+2*x+1  #6x+2

In [12]:
result=numerical_derivative(my_func3,2)
print("result ==",result)

result == 14.000000000020663


In [23]:
import numpy as np

def numerical_derivative(f,x):
    delta_x=1e-4
    grad=np.zeros_like(x)
    print("debug1. initial input variable =",x)
    print("debug2. initial grad =",grad)
    print("==============================================")
    
    it=np.nditer(x,flags=['multi_index'],op_flags=['readwrite'])
    
    while not it.finished:
        idx=it.multi_index
        print("debug3. idx= ", idx, ", x[idx] =",x[idx])
        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        print("debug4. grad[idx] =",grad[idx])
        print("debug5. grad =",grad)
        print("==============================================")
        
        x[idx] = tmp_val
        it.iternext() 
        
    return grad

In [20]:
def func1(input_obj):
    x=input_obj[0]
    return x**2

numerical_derivative(func1,np.array([3.0]))

debug1. initial input variable = [3.]
debug2. initial grad = [0.]
debug3. idx=  (0,) , x[idx] = 3.0
debug . grad[idx] = 6.000000000012662
debug5. grad = [6.]


array([6.])

In [25]:
#2x+3xy+y^3
def func2(input_obj):
    x=input_obj[0]
    y=input_obj[1]
    return (2*x+3*x*y+np.power(y,3))

input=np.array([1.0,2.0])

numerical_derivative(func2,input)

debug1. initial input variable = [1. 2.]
debug2. initial grad = [0. 0.]
debug3. idx=  (0,) , x[idx] = 1.0
debug4. grad[idx] = 7.999999999990237
debug5. grad = [8. 0.]
debug3. idx=  (1,) , x[idx] = 2.0
debug4. grad[idx] = 15.000000010019221
debug5. grad = [ 8.         15.00000001]


array([ 8.        , 15.00000001])

In [27]:
#wx+xyz+3w+zy^2
def func3(input_obj):
    w=input_obj[0,0]
    x=input_obj[0,1]
    y=input_obj[1,0]
    z=input_obj[1,1]
    return (w*z+x*y*z+3*w+z*np.power(y,2))

#입력을 2X2 godfuffh rntjd
input=np.array([[1.0,2.0],[3.0,4.0]])

numerical_derivative(func3,input)

debug1. initial input variable = [[1. 2.]
 [3. 4.]]
debug2. initial grad = [[0. 0.]
 [0. 0.]]
debug3. idx=  (0, 0) , x[idx] = 1.0
debug4. grad[idx] = 6.999999999948159
debug5. grad = [[7. 0.]
 [0. 0.]]
debug3. idx=  (0, 1) , x[idx] = 2.0
debug4. grad[idx] = 12.000000000043087
debug5. grad = [[ 7. 12.]
 [ 0.  0.]]
debug3. idx=  (1, 0) , x[idx] = 3.0
debug4. grad[idx] = 32.00000000006753
debug5. grad = [[ 7. 12.]
 [32.  0.]]
debug3. idx=  (1, 1) , x[idx] = 4.0
debug4. grad[idx] = 15.99999999996271
debug5. grad = [[ 7. 12.]
 [32. 16.]]


array([[ 7., 12.],
       [32., 16.]])