In [1]:
def numerical_derivative(f,x):
    delta_x = 1e-4
    return (f(x+delta_x)-f(x-delta_x))/(2*delta_x)

In [2]:
def my_func1(x):
    return x**2

In [4]:
result=numerical_derivative(my_func1,3)
print("result ==",result)

result == 6.000000000012662


In [5]:
import numpy as np

def my_func2(x):
    return 3*x*(np.exp(x))

In [6]:
result=numerical_derivative(my_func2,2)
print("result ==",result)

result == 66.50150507518049


In [7]:
print("3*exp(2)+3*2*exp(2)==",end='')
print(3*np.exp(2)+3*2*np.exp(2))

3*exp(2)+3*2*exp(2)==66.50150489037586


In [11]:
def my_func3(x):
    return 3*x**2+2*x+1  #6x+2

In [12]:
result=numerical_derivative(my_func3,2)
print("result ==",result)

result == 14.000000000020663


In [23]:
import numpy as np

def numerical_derivative(f,x):
    delta_x=1e-4
    grad=np.zeros_like(x)
    print("debug1. initial input variable =",x)
    print("debug2. initial grad =",grad)
    print("==============================================")
    
    it=np.nditer(x,flags=['multi_index'],op_flags=['readwrite'])
    
    while not it.finished:
        idx=it.multi_index
        print("debug3. idx= ", idx, ", x[idx] =",x[idx])
        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        print("debug4. grad[idx] =",grad[idx])
        print("debug5. grad =",grad)
        print("==============================================")
        
        x[idx] = tmp_val
        it.iternext() 
        
    return grad

In [20]:
def func1(input_obj):
    x=input_obj[0]
    return x**2

numerical_derivative(func1,np.array([3.0]))

debug1. initial input variable = [3.]
debug2. initial grad = [0.]
debug3. idx=  (0,) , x[idx] = 3.0
debug . grad[idx] = 6.000000000012662
debug5. grad = [6.]


array([6.])

In [25]:
#2x+3xy+y^3
def func2(input_obj):
    x=input_obj[0]
    y=input_obj[1]
    return (2*x+3*x*y+np.power(y,3))

input=np.array([1.0,2.0])

numerical_derivative(func2,input)

debug1. initial input variable = [1. 2.]
debug2. initial grad = [0. 0.]
debug3. idx=  (0,) , x[idx] = 1.0
debug4. grad[idx] = 7.999999999990237
debug5. grad = [8. 0.]
debug3. idx=  (1,) , x[idx] = 2.0
debug4. grad[idx] = 15.000000010019221
debug5. grad = [ 8.         15.00000001]


array([ 8.        , 15.00000001])

In [27]:
#wx+xyz+3w+zy^2
def func3(input_obj):
    w=input_obj[0,0]
    x=input_obj[0,1]
    y=input_obj[1,0]
    z=input_obj[1,1]
    return (w*z+x*y*z+3*w+z*np.power(y,2))

#입력을 2X2 godfuffh rntjd
input=np.array([[1.0,2.0],[3.0,4.0]])

numerical_derivative(func3,input)

debug1. initial input variable = [[1. 2.]
 [3. 4.]]
debug2. initial grad = [[0. 0.]
 [0. 0.]]
debug3. idx=  (0, 0) , x[idx] = 1.0
debug4. grad[idx] = 6.999999999948159
debug5. grad = [[7. 0.]
 [0. 0.]]
debug3. idx=  (0, 1) , x[idx] = 2.0
debug4. grad[idx] = 12.000000000043087
debug5. grad = [[ 7. 12.]
 [ 0.  0.]]
debug3. idx=  (1, 0) , x[idx] = 3.0
debug4. grad[idx] = 32.00000000006753
debug5. grad = [[ 7. 12.]
 [32.  0.]]
debug3. idx=  (1, 1) , x[idx] = 4.0
debug4. grad[idx] = 15.99999999996271
debug5. grad = [[ 7. 12.]
 [32. 16.]]


array([[ 7., 12.],
       [32., 16.]])

In [72]:
import numpy as np

#x_data = np.array([1,2,3,4,5]).reshape(5,1) #W=1, b=1, y=Wx+1
#t_data = np.array([2,3,4,5,6]).reshape(5,1)

x_data=np.array([9,14,21,27,32,37]).reshape(6,1)
t_data=np.array([74,81,86,90,88,92]).reshape(6,1)

#raw_data [[1,2],[2,3],[3,4],[4,5],[5,6]]
print('x_data.shpae=',x_data.shape,', t_data.shape=',t_data.shape)

x_data.shpae= (6, 1) , t_data.shape= (6, 1)


In [73]:
W=np.random.rand(1,1)
b=np.random.rand(1)
print('W=',W,', W.shape=',W.shape,', b=',b,', b.shape=',b.shape)

W= [[0.81084396]] , W.shape= (1, 1) , b= [0.0479357] , b.shape= (1,)


In [56]:
def loss_func(x,t):
    y=np.dot(x,W)+b
    return (np.sum((t-y)**2))/(len(x))

In [57]:
def numerical_derivative(f,x):
    delta_x=1e-4
    grad=np.zeros_like(x)
    #print("debug1. initial input variable =",x)
    #print("debug2. initial grad =",grad)
    #print("==============================================")
    
    it=np.nditer(x,flags=['multi_index'],op_flags=['readwrite'])
    
    while not it.finished:
        idx=it.multi_index
        #print("debug3. idx= ", idx, ", x[idx] =",x[idx])
        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        #print("debug4. grad[idx] =",grad[idx])
        #print("debug5. grad =",grad)
        #print("==============================================")
        
        x[idx] = tmp_val
        it.iternext() 
        
    return grad

In [58]:
def error_val(x,t):
    y=np.dot(x,W)+b
    return (np.sum((t-y)**2))/(len(x))

In [59]:
#학습을 마친 후, 임의 데이터에 대해 미래 값 예측 함수
def predict(x):
    y=np.dot(x,W)+b
    return y

In [77]:
#learning_rate=1e-2 #발산하는 경우, 1e-3 ~ 1e-6 등으로 바꿔서 실행
learning_rate=1e-3

f=lambda x : loss_func(x_data,t_data) #f(x)=loss_funcs(x_data,t_data)

print('Initial error value=',error_val(x_data,t_data),'Initial W=',W,'\n',',b=',b)

for step in range(30001):
    W-=learning_rate*numerical_derivative(f,W)
    b-=learning_rate*numerical_derivative(f,b)
    
    if(step%500==0):
        print('step=',step,', error value=',error_val(x_data,t_data),', W=',W,', b=',b)

Initial error value= 4.634883721011157 Initial W= [[0.58023341]] 
 ,b= [71.62788369]
step= 0 , error value= 4.634883721011117 , W= [[0.58023341]] , b= [71.6278837]
step= 500 , error value= 4.634883720990236 , W= [[0.58023329]] , b= [71.62788693]
step= 1000 , error value= 4.634883720974734 , W= [[0.58023319]] , b= [71.62788971]
step= 1500 , error value= 4.634883720963247 , W= [[0.5802331]] , b= [71.62789211]
step= 2000 , error value= 4.634883720954703 , W= [[0.58023303]] , b= [71.62789417]
step= 2500 , error value= 4.634883720948386 , W= [[0.58023296]] , b= [71.62789595]
step= 3000 , error value= 4.63488372094371 , W= [[0.5802329]] , b= [71.62789748]
step= 3500 , error value= 4.634883720940237 , W= [[0.58023286]] , b= [71.6278988]
step= 4000 , error value= 4.6348837209376565 , W= [[0.58023282]] , b= [71.62789993]
step= 4500 , error value= 4.634883720935732 , W= [[0.58023278]] , b= [71.62790091]
step= 5000 , error value= 4.634883720934303 , W= [[0.58023275]] , b= [71.62790175]
step= 5500

In [78]:
predict(30)

array([[89.03488372]])